<?php

declare(strict_types=1);

/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sindri\Generator\Ast\Cli;

use Override;
use PhpParser\Node\Expr;
use PhpParser\PrettyPrinter\Standard;
use PhpParser\PrettyPrinterAbstract;
use Sindri\Generator\Abstract\FileGenerator;
use Sindri\Generator\Cli\Contract\DataFileGeneratorContract;
use Valkyrja\Cli\Routing\Data\CliRoutingData;
use Valkyrja\Cli\Routing\Data\Contract\RouteContract;

/**
 * AST-based CLI routing data file generator.
 *
 * Accepts PHP-Parser Expr nodes produced by CliRouteAttributeReader and pretty-prints
 * them directly into the generated data class, bypassing any runtime app boot.
 */
class AstCliDataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string    $directory
     * @param array<string, Expr> $routes
     * @param non-empty-string    $namespace
     * @param non-empty-string    $className
     */
    public function __construct(
        string $directory,
        protected array $routes,
        protected string $namespace,
        string $className,
        protected PrettyPrinterAbstract $printer = new Standard(),
    ) {
        parent::__construct(directory: $directory, className: $className);
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $namespace   = $this->namespace;
        $className   = $this->className;
        $routingData = CliRoutingData::class;
        $routes      = $this->getRoutesAsContent();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by Sindri.

            namespace $namespace;

            use $routingData;

            final readonly class $className extends CliRoutingData
            {
                public function __construct()
                {
                    parent::__construct(
                        routes: $routes,
                    );
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = 'Sindri\Cli\Data\CliRoutingData';
        $routes        = $this->getRoutesAsContent();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                routes: $routes,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Pretty-print all routes into a PHP array literal string.
     *
     * @return non-empty-string
     */
    protected function getRoutesAsContent(): string
    {
        $routeContract = RouteContract::class;
        $routesContent = '';

        foreach ($this->routes as $key => $routeExpr) {
            $routePhp       = $this->printer->prettyPrintExpr($routeExpr);
            $routesContent .= <<<PHP
                '$key' => static fn (): \\$routeContract => $routePhp,

                PHP;
        }

        return <<<PHP
            [
                $routesContent
            ]
            PHP;
    }
}
