<?php

declare(strict_types=1);

/*
 * This file is part of the Sindri package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sindri\Generator\Ast\Event;

use Override;
use PhpParser\Node\Expr;
use PhpParser\PrettyPrinter\Standard;
use PhpParser\PrettyPrinterAbstract;
use Sindri\Generator\Abstract\FileGenerator;
use Sindri\Generator\Event\Contract\DataFileGeneratorContract;
use Valkyrja\Event\Data\Contract\ListenerContract;
use Valkyrja\Event\Data\EventData;

/**
 * AST-based event data file generator.
 *
 * Accepts PHP-Parser Expr nodes produced by ListenerAttributeReader and pretty-prints
 * them directly into the generated data class, bypassing any runtime app boot.
 */
class AstEventDataFileGenerator extends FileGenerator implements DataFileGeneratorContract
{
    /**
     * @param non-empty-string    $directory
     * @param array<string, Expr> $listeners
     * @param non-empty-string    $namespace
     * @param non-empty-string    $className
     */
    public function __construct(
        string $directory,
        protected array $listeners,
        protected string $namespace,
        string $className,
        protected PrettyPrinterAbstract $printer = new Standard(),
    ) {
        parent::__construct(directory: $directory, className: $className);
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $namespace = $this->namespace;
        $className = $this->className;
        $eventData = EventData::class;
        $listeners = $this->getListenersAsContent();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by Sindri.

            namespace $namespace;

            use $eventData;

            final readonly class $className extends EventData
            {
                public function __construct()
                {
                    parent::__construct(
                        events: [],
                        listeners: $listeners,
                    );
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace = EventData::class;
        $listeners     = $this->getListenersAsContent();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                events: [],
                listeners: $listeners,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Pretty-print all listeners into a PHP array literal string.
     *
     * @return non-empty-string
     */
    protected function getListenersAsContent(): string
    {
        $listenerContract = ListenerContract::class;
        $listenersContent = '';

        foreach ($this->listeners as $key => $listenerExpr) {
            $listenerPhp       = $this->printer->prettyPrintExpr($listenerExpr);
            $listenersContent .= <<<PHP
                '$key' => static fn (): \\$listenerContract => $listenerPhp,

                PHP;
        }

        return <<<PHP
            [
                $listenersContent
            ]
            PHP;
    }
}
