<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sindri\Tests\Unit\Generator\Http;

use Sindri\Generator\Enum\GenerateStatus;
use Sindri\Generator\Http\DefaultDataProviderFileGenerator;
use Sindri\Tests\Unit\Abstract\TestCase;
use Valkyrja\Application\Directory\Directory;

final class DefaultDataProviderFileGeneratorTest extends TestCase
{
    public function testGenerateFile(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'HttpRoutingDataTestDataProvider';
        $filePath   = "$directory/$className.php";
        $generator  = new DefaultDataProviderFileGenerator(
            directory: $directory,
            namespace: 'App',
            className: $className
        );
        $results   = $generator->generateFile();

        self::assertSame(GenerateStatus::SUCCESS, $results);
        self::assertSame($generator->generateFileContents(), @file_get_contents($filePath));

        @unlink($filePath);
    }

    public function testGenerateFileContents(): void
    {
        $directory  = Directory::storagePath();
        $className  = 'HttpRoutingDataTestDataProvider';
        $namespace  = 'App';
        $generator  = new DefaultDataProviderFileGenerator(
            directory: $directory,
            namespace: $namespace,
            className: $className
        );
        $contents  = $generator->generateFileContents();

        $expected = <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by the Valkyrja Framework.

            namespace $namespace;

            use Override;
            use Valkyrja\Http\Routing\Data\HttpRoutingData;
            use Valkyrja\Container\Provider\Contract\ServiceProviderContract;
            use Valkyrja\Container\Manager\Contract\ContainerContract;
            use Valkyrja\Http\Routing\Provider\HttpRoutingServiceProvider;

            final class HttpRoutingDataTestDataProvider implements ServiceProviderContract
            {
                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function publishers(): array
                {
                    return [
                        HttpRoutingData::class => [self::class, 'publishData'],
                    ];
                }

                /**
                 * @inheritDoc
                 */
                #[Override]
                public static function provides(): array
                {
                    return [
                        HttpRoutingData::class,
                    ];
                }

                /**
                 * Publish the service.
                 */
                public static function publishData(ContainerContract \$container): void
                {
                    HttpRoutingServiceProvider::publishData(\$container);
                }
            }

            PHP;

        self::assertNotEmpty($contents);
        self::assertSame($expected, $contents);
    }
}
