<?php

declare(strict_types=1);

/*
 * This file is part of the Valkyrja Framework package.
 *
 * (c) Melech Mizrachi <melechmizrachi@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Sindri\Generator\Ast\Container;

use Override;
use Sindri\Generator\Abstract\FileGenerator;
use Sindri\Generator\Container\Contract\ContainerDataFileGeneratorContract;
use Valkyrja\Container\Data\ContainerData;

/**
 * AST-based container data file generator.
 *
 * Accepts the publishers map extracted by ServiceProviderReader and emits
 * a ContainerData subclass using ::class syntax rather than string literals,
 * bypassing any runtime app boot.
 *
 * Only deferredCallback is populated; deferred and providers are left empty
 * because deferredCallback alone is sufficient for the container to resolve
 * deferred bindings, and the provider list is managed by the app config.
 */
class AstContainerDataFileGenerator extends FileGenerator implements ContainerDataFileGeneratorContract
{
    /**
     * @param non-empty-string                                       $directory
     * @param array<class-string, array{0: class-string, 1: string}> $publishers
     * @param non-empty-string                                       $namespace
     * @param non-empty-string                                       $className
     */
    public function __construct(
        string $directory,
        protected array $publishers,
        protected string $namespace,
        string $className,
    ) {
        parent::__construct(directory: $directory, className: $className);
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateFileContents(): string
    {
        $namespace        = $this->namespace;
        $className        = $this->className;
        $containerData    = ContainerData::class;
        $deferredCallback = $this->getDeferredCallbackContent();

        return <<<PHP
            <?php

            declare(strict_types=1);

            // This file was automatically generated by Sindri.

            namespace $namespace;

            use $containerData;

            final readonly class $className extends ContainerData
            {
                public function __construct()
                {
                    parent::__construct(
                        deferredCallback: $deferredCallback,
                    );
                }
            }

            PHP;
    }

    /**
     * @inheritDoc
     */
    #[Override]
    public function generateClassContents(): string
    {
        $dataNamespace    = ContainerData::class;
        $deferredCallback = $this->getDeferredCallbackContent();

        // phpcs:disable
        return <<<PHP
            new \\$dataNamespace(
                deferredCallback: $deferredCallback,
            )
            PHP;
        // phpcs:enable
    }

    /**
     * Pretty-print all publisher entries as a PHP array literal using ::class syntax.
     *
     * @return non-empty-string
     */
    protected function getDeferredCallbackContent(): string
    {
        $content = '';

        foreach ($this->publishers as $serviceClass => [$providerClass, $method]) {
            $content .= <<<PHP
                \\$serviceClass::class => [\\$providerClass::class, '$method'],

                PHP;
        }

        return <<<PHP
            [
                $content]
            PHP;
    }
}
